### ISSUE TITLE
Maybe add Gemfile.lock to gitignore?

### ISSUE THREAD

**Issue by charnpreetsingh** [jupyter/jupyter.github.io#167]
I was trying to work on the website today and kept getting this error:
```
/Library/Ruby/Gems/2.0.0/gems/bundler-1.13.6/lib/bundler/definition.rb:179:in `rescue in specs': Your bundle is locked to minitest (5.9.1), but that version could not be found in any of the sources listed in your Gemfile. If you haven't changed sources, that means the author of minitest (5.9.1) has removed it. You'll need to update your bundle to a different version of minitest (5.9.1) that hasn't been removed in order to install. (Bundler::GemNotFound)
	from /Library/Ruby/Gems/2.0.0/gems/bundler-1.13.6/lib/bundler/definition.rb:173:in `specs'
	from /Library/Ruby/Gems/2.0.0/gems/bundler-1.13.6/lib/bundler/definition.rb:233:in `specs_for'
	from /Library/Ruby/Gems/2.0.0/gems/bundler-1.13.6/lib/bundler/definition.rb:222:in `requested_specs'
	from /Library/Ruby/Gems/2.0.0/gems/bundler-1.13.6/lib/bundler/runtime.rb:118:in `block in definition_method'
	from /Library/Ruby/Gems/2.0.0/gems/bundler-1.13.6/lib/bundler/runtime.rb:19:in `setup'
	from /Library/Ruby/Gems/2.0.0/gems/bundler-1.13.6/lib/bundler.rb:99:in `setup'
	from /Library/Ruby/Gems/2.0.0/gems/jekyll-3.3.0/lib/jekyll/plugin_manager.rb:36:in `require_from_bundler'
	from /Library/Ruby/Gems/2.0.0/gems/jekyll-3.3.0/exe/jekyll:9:in `<top (required)>'
	from /usr/local/bin/jekyll:22:in `load'
	from /usr/local/bin/jekyll:22:in `<main>'
```

It's forcing me to use an older version of a ruby gem. Removing the Gemfile.lock file allowed me to get around this.  Any thoughts?

**Comment by Carreau** [comment]
use bundler, do a `bundle install`, and then `bundle exec <usual command>` it will install all dependencies locally in  asubfolder without touching your global ruby installation.

**Comment by charnpreetsingh** [comment]
@Carreau I understand that but each time you do `bundle install` it will be installing the latest dependencies and update `Gemfile.lock` accordingly. The `Gemfile` is more so for Travis CI tests rather than local development.

**Comment by Carreau** [comment]
Oh, yes sure, then.

**Comment by charnpreetsingh** [comment]
Closing via #169
