### ISSUE TITLE
I can open a jupyter notebook, but I cannot run the notebook with python script in it on my Mac

### ISSUE THREAD

**Issue by bjce** [jupyter/jupyter.github.io#326]
I have been using jupyter as well as Atom with python for more than a year now. I'm currently using Python 3.7.2 on macOS 10.14. There is no problem running Python from the Terminal and here are the PATH I get after running `sys.path`:

```
['', '/Library/Frameworks/Python.framework/Versions/3.7/lib/python37.zip', '/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7', '/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/lib-dynload', '/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages']
```

I can open a jupyter notebook in jupyter but for some obscure reason, I cannot run the notebook and there is a red `Kernel error` on the top right of the page with the following error message when I click on it: 

```
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/tornado/web.py", line 1699, in _execute
    result = await result
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/tornado/gen.py", line 736, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/notebook/services/sessions/handlers.py", line 73, in post
    type=mtype))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/tornado/gen.py", line 729, in run
    value = future.result()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/tornado/gen.py", line 736, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/notebook/services/sessions/sessionmanager.py", line 79, in create_session
    kernel_id = yield self.start_kernel_for_session(session_id, path, name, type, kernel_name)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/tornado/gen.py", line 729, in run
    value = future.result()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/tornado/gen.py", line 736, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/notebook/services/sessions/sessionmanager.py", line 92, in start_kernel_for_session
    self.kernel_manager.start_kernel(path=kernel_path, kernel_name=kernel_name)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/tornado/gen.py", line 729, in run
    value = future.result()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/tornado/gen.py", line 209, in wrapper
    yielded = next(result)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/notebook/services/kernels/kernelmanager.py", line 160, in start_kernel
    super(MappingKernelManager, self).start_kernel(**kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/jupyter_client/multikernelmanager.py", line 110, in start_kernel
    km.start_kernel(**kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/jupyter_client/manager.py", line 259, in start_kernel
    **kw)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/jupyter_client/manager.py", line 204, in _launch_kernel
    return launch_kernel(kernel_cmd, **kw)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/jupyter_client/launcher.py", line 138, in launch_kernel
    proc = Popen(cmd, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 1522, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
PermissionError: [Errno 13] Permission denied: '/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7'
```
here is my PATH (obtained after the command: `nano ~/.bash_profile`)
```
# Homebrew
export PATH=/usr/local/bin:$PATH

# Setting PATH for Python 3.7
# The original version is saved in .bash_profile.pysave
PATH="/Library/Frameworks/Python.framework/Versions/3.7/bin:${PATH}"
export PATH

# Setting PATH for Python 3.7
# The original version is saved in .bash_profile.pysave
PATH="/Library/Frameworks/Python.framework/Versions/3.7/bin:${PATH}"
export PATH

```
I already uninstalled all the python installations on my computer including the anaconda version (except python 2.7 as my mac doesn't accept that I remove it)

**Comment by choldgraf** [comment]
hey @bjce - it looks like your Jupyter process is trying to run a Python executable that it doesn't have the permissions to access:

```
/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7
```

I'd recommend re-installing the Anaconda distribution, making sure that calling `python` as well as calling `jupyter` is using the ones that are bundled with Anaconda, and then re-trying opening a notebook.

(also, just a note that this repository is only to discuss the jupyter.org website, somebody with permission should move this to the `notebook` repo)

**Comment by bjce** [comment]
Thank you very much for your quick answer @choldgraf. As I mentioned in my question, I removed manually all the other python installation including anaconda to start afresh (which might be the cause of the problem). If possible, in order to avoid a thousand different python installation path which already caused my a lot of headache and time, I would like to install jupyter notebook WITHOUT anaconda. Is it at all possible?

**Comment by choldgraf** [comment]
it is possible but can be more complicated (since really the question would be "how can I install Python on my computer in a way that I can access it?"). I'd recommend following the [Jupyter Notebook install instructions](https://jupyter.org/install)

**Comment by bjce** [comment]
thanks again @choldgraf. I already followed the instructions on this website and ran 

```
python3 -m pip install --upgrade pip
python3 -m pip install jupyter
```

but it didn't solve the problem

**Comment by choldgraf** [comment]
try typing `which python3` and see where it points...then type in `which jupyter` and make sure it's the same Python folder.

Also note that those `pip` instructions are assuming that you already have a functioning Python installation - the problem here is that you don't currently have a functioning Python installation (that's why the jupyter install docs recommend using Anaconda as a first step)

**Comment by bjce** [comment]
many thanks @choldgraf. In the meantime, I uninstalled everything and re-installed python and jupyter  through homebrew and so far it works. Many thanks for your time

**Comment by choldgraf** [comment]
that's great news! happy to help. think we can close this issue?

**Comment by bjce** [comment]
yes. I closed the issue. thank you very much again @choldgraf
